Bankmanagement/urls.py
from django.contrib import admin
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('profile/', include("Profile.urls")),
    path('admins/', include("admins.urls")),
    path('email/',include('mail.urls')),
    path('', views.index, name ="home"),


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Profile/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "Profile"

urlpatterns = [
    path("account_status/", views.index, name = "account_status"),
    path("edit_detail/", views.edit_detail, name = "edit_detail"),
    path("settings/",views.settings,name="settings"),
    path("delete_account/",views.delete_account,name="delete_account"),
    path("money_transfer/", views.money_transfer, name = "money_transfer"),
    path("loan_app/", views.loan, name = "loan_app"),
    path("ewallet/", views.ewallet, name = "ewallet"),
    path("online_pay/", views.online_pay, name = "online_pay"),
    # path("deposit/", views.DepositMoney, name="deposit_money"),
    # path("withdraw/", views.WithdrawMoney, name="withdraw_money"),
    




]

accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name = "signup"),
    path("login/", views.sign_in, name = "signin"),
    path("logout/", views.logout_view, name = "logout"),




]

mail/urls.py
from django.urls import path
from mail.views import *

urlpatterns = [
    path('email/',form),
 
]

Profile/models.py
from django.db import models

# Create your models here.
class BasicDetails(models.Model):
    name = models.CharField(max_length = 50)
    sex = models.CharField(max_length = 1)
    annual_income = models.IntegerField()
    email = models.EmailField(max_length=255)
    mobile = models.IntegerField()
    occupation = models.CharField(max_length = 50)
    DOB = models.DateField()
    user_name = models.CharField(max_length = 150)
    aadhar=models.IntegerField()
    image=models.ImageField(upload_to ='uploads/Photo')

class PresentLocation(models.Model):
    country = models.CharField(max_length = 50, default = "India")
    state = models.CharField(max_length = 50)
    city = models.CharField(max_length = 50)
    street = models.CharField(max_length = 50)
    pincode = models.IntegerField()
    user_name = models.CharField(max_length = 150)

class Status (models.Model):
    account_number = models.IntegerField()
    balance = models.IntegerField()
    user_name = models.CharField(max_length = 150)

class Email(models.Model):
    To=models.CharField(max_length = 150)
    subject=models.CharField(max_length=200)

Profile/forms.py
from django import forms
from . import models

class BasicDetailsForm (forms.ModelForm):
  
    class Meta:
        model = models.BasicDetails
        fields = ["name", "sex", "DOB", "annual_income", "email", "mobile", "occupation"]


class PresentLocationForm (forms.ModelForm):
    class Meta:
        model = models.PresentLocation
        fields = ["country", "state", "city", "street", "pincode"]

Profile/views.py
from django.shortcuts import render,redirect
from . import forms
from . import models
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from Profile.models import Status
import random
import sys
# Create your views here.
def randomGen():
    return int(random.uniform(100000000000, 999999999999))

def index(request):
    try:
        curr_user=Status.objects.get(user_name=request.user)
    except:
        curr_user=Status()
        curr_user.account_number=randomGen()
        curr_user.balance=0
        curr_user.user_name=request.user
        curr_user.save()
    return render(request,'Profile.html',{"curr_user":curr_user})
def edit_detail(request):
    #post actions for BasicDetailsForms
    if request.method=="POST":
        try:
            curr_user=models.BasicDetails.objects.get(user_name=request.user)
            form=forms.BasicDetailsForm(request.POST,instance=curr_user)
            if form.is_valid():
                form.save
        except:
            form=forms.BasicDetailsForm(request.POST)
            if form.is_valid():
                form=form.save(commit=False)
                form.user_name=request.user
                form.save()


        #post action for present location
        try:
            curr_user=models.PresentLocation.objects.get(user_name=request.user)
            form=forms.PresentLocationForm(request.POST,instance=curr_user)
            if form.is_valid():
                form.save()
        except:
            form=forms.PresentLocationForm(request.POST)
            if form.is_valid():
                form=form.save(commit=False)
                form.user_name=request.user
                form.save()

        #post action for password change
        form=PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user=form.save()
            update_session_auth_hash(request,user)
            messages.success(request,'Your password was successfully changed')
            return redirect('edit_detail.html')
        else:
            messages.error(request,'Please correct the error')
        return redirect('edit_detail.html')
    else:
        try:
            curr_user=models.BasicDetails.objects.get(user_name=request.user)
            form1=forms.BasicDetailsForm(instance=curr_user)
        except:
            form1=forms.BasicDetailsForm()
        try:
            curr_user=models.PresentLocation.objects.get(user_name=request.user)
            form2=forms.PresentLocationForm(instance=curr_user)
        except:
            form2=forms.PresentLocationForm()
        #change password
        dici={"form1":form1,"form2":form2,"form3":form3}
        return render(request,'edit_detail.html',dici)


def money_transfer(request):
    return render(request,'money_transfer.html')


def loan(request):
    return render(request, "loans.html")


def ewallet(request):
    return render(request, "eWallet.html")


def online_pay(request):
    return render(request, "online_payment.html")


def settings(request):
    return render(request, "settings.html")


def delete_account(request):
    return render(request,'Delete_account.html')


class Customer:

    bankname="SBI"
    def __init__(self,name,balance=0.0):
        self.name=name
        self.balance=balance
    def deposit(self,amt):
        self.balance=self.balance+amt
        print("Balance after Deposit:",self.balance)
    def withdraw(self,amt):
        if amt>self.balance:
            print("insufficient Funds..cannot Perform this operations")
            sys.exit()
        self.balance=self.balance-amt
        print('Balance after withdraw"',self.balance)
print('Welcome to',Customer.bankname)
name=input("Enter your name:")
c=Customer(name)

templates/admin.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bank Management | Admin Page</title>

        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <!-- STYLINGS -->
        <link rel="stylesheet" href="/static/common-styles.css">
        <style>
            @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');

            body {
                background-color: floralwhite;
            }
            h2 {
                font-family: "PT Serif";
            }
            h3, h4 {
                font-weight: 300;
            }
            #delete-acc {
                border-bottom: 1px solid;
            }

            #side_panel
            {
                font-size: 16px;
                font-family: "Titillium Web";
                background-color: rgb(170, 95, 57);
                margin-top: -7px;
                margin-left: -10px;
                height: 540px;
                overflow-x: auto;
                overflow-y: auto;
            }

            .side {
                color: aliceblue;
            }
            .side:hover {
                color: mediumaquamarine;
            }
            .warning {
                color: yellow;
            }
            .danger {
                color: #FF8723;
                font-weight: 900;
            }
            .current {
                border: 1px solid;
                padding: 3px;
            }
            .curr_bal {
                font-family: "Cinzel";
                font-weight: 600;
            }

            table::-webkit-scrollbar {
                width: 3px;
            }
            table::-webkit-scrollbar:hover {
                width: 3px;
            }
            table::-webkit-scrollbar-track {
                -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
                border-radius: 10px;
            }
            ::-webkit-scrollbar-thumb {
                border-radius: 10px;
                -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
            }
        </style>

        <script src='https://www.google.com/recaptcha/api.js'></script>

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: goldenrod">
            <img src="/static/images/logo.jpg" width="50px">
            <a class="navbar-brand" href="index.html">&nbsp;Bank Managenent</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="index.html">Logout</a>
                </div>
            </div>
        </nav>

        <br> <br> <br>

        <div class="container-fluid">
            <section id="welcome_post">
                <h3>
                    Welcome.
                </h3>
                <br>



        <!-- FOOTER -->
        <section class="foot">
            <div class="text-center">
                &copy; <i class="" style="color: green"></i> by <a href="" target="_blank"></a>  
                <br>
                <i class=""></i><a href="" target="_blank"></a>
            </div>
        </section>

        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
</html>

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Bank Management</title>

        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        {% block stylecontent %}

        {% endblock %}
        
        <link rel="stylesheet" href="/static/common-styles.css">

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
            <img src="/static/images/logo.jpg" width="50px">
            <a class="navbar-brand" href="{% url 'home' %}">&nbsp;Bank Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'home' %}" id="nav-home">Home</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}" id="nav-create">Create new account</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signin' %}" id="nav-login">Log in</a>

                </div>
            </div>
        </nav>

        <br> <br> <br>

        {% block bodycontent %}

        {% endblock %}

        <!-- FOOTER -->
        <section class="foot">
            <div class="text-center">
                <i class="fa fa" style="color: green"></i>
                <br>
                <i class="fa fa"></i>
            </div>
        </section>

        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}

    </body>
</html>

templates/create_account.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Slabo+27px');

        body {
            background-color: aliceblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        form ul {
            list-style: none;
        }
    </style>


    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}


{% block bodycontent %}
    <h2 class="container text-center">Create New Account</h2>
    <h6 class="text-center"><em>(All details are mandatory)</em></h6>
    <br>

    <form class="container" action="/accounts/register/" method="post">
        {% csrf_token %}
        <section class="form-control">
            <h4>Enter basic details</h4>
            {{ form }}
        </section>
        <br>
        <br>

        <section>
            <input type="checkbox" required>
            <small>By clicking "Create account" you agree to our
                <a href="#">Terms and Conditions</a>.</small>
        </section>

        <br>

        <input type="submit" class="form-control btn btn-primary" value="Create account" name="submit"
        />

    </form>

    <br>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-create").addClass("active");

        $(".helptext").html("");

        var input_text = $("input[type=text]");
        input_text.addClass("form-control");

        var input_pass = $("input[type=password]");
        input_pass.addClass("form-control");

        $("form ul li").addClass("btn btn-danger");
    </script>
{% endblock %}

templates/delete_account.html
{% extends 'profile_base_layout.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        .g-recaptcha {
            width: 50px;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
    
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

{% block bodycontent %}
    <section id="welcome_post" class="col-9">   
        <h3 style="font-weight: 300;" >Deleting the account means:</h3>
        <ul type="square">
            <li>Permanent loss of your account balance (so <a href="{% url 'profiles:money_transfer' %}">transfer your money</a> to a different account first). </li>
            <li>Permanent loss of your account data, settings, and details.</li>
        </ul>

        <h3 style="font-weight: 300;" >By pressing the following button, you understand the shortcomings as described in <a href="#">here</a>. </h3>
        
        
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#delete" >
            Take me to deletion
        </button>

        <!-- Modal -->
        <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="delete" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirm deletion</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form>
                    <div class="modal-body">
                        Enter password to confirm deletion
                        <input type="password" class="form-control" required>
                        <br>
                        Prove you are a human
                        <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Delete my account</button>
                    </div>
                </form>
                
            </div>
            </div>
        </div>
        
        
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#delete").addClass("current");
    </script>
{% endblock %}

templates/form.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>E-MAIL</title>
  </head>
  <body>
    <h1>E-mail</h1>
    <form method="POST" action="/">
        {% csrf_token %}
        <div class="form-group">
          <label for="exampleInputEmail1">Email address</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email" placeholder="Enter email">
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label for="exampleInputPassword1">message</label>
          <input type="text" class="form-control" id="exampleInputPassword1" name="message" placeholder="text">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
    <style>
        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }

        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}


{% block bodycontent %}
    <div class="container text-center">
        <h1>Welcome to Black money Bank</h1>
        <h4><em>We operate 24*7</em></h4>
    </div>

    <br>

    <div class="container">
        <a href="{% url 'accounts:signup' %}"><button class="btn btn-warning btn-block" id="acc"><i class="fa fa-file-text"></i> Create new account</button></a>
        <br>
        <a href="{% url 'accounts:signin' %}"><button class="btn btn-success btn-block" id="sign_in"><i class="fa fa-sign-in"></i> Log in</button></a>
    </div>

    <br>
{% endblock %}

templates/profile_base_layout.html
{ % load static from staticfiles % }

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Bank Management | Profile</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        <!-- STYLINGS -->
        <link rel="stylesheet" href="/static/common-styles.css">

        {% block headcontent %}
        {% endblock %}

    </head>

    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: goldenrod">
            <img src="/static/images/logo.jpg" width="50px">
            <a class="navbar-brand" href="index.html">&nbsp;Bank Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    <a class="nav-item nav-link active" href="{% url 'Profile:deposit_money' %}" id="nav-Deposit">Deposit</a>
                    <a class="nav-item nav-link" href="{% url 'Profile:withdraw_money' %}" id="nav-Withdrawl">Withdrawl</a>
                </div>
            </div>
        </nav>

        <br> <br> <br>

        <div class="container-fluid row">

                <!--SIDE PANEL BEGINS -->
                <section id="side_panel" class="col-3">
                    <img src="/static/images/logo.jpg" class="container btn">
                    <!-- OPERATIONS -->
                    <a href="{% url 'Profile:account_status' %}" class="current side" id="status">Account status</a> <br> <br>

                    <a href="{% url 'Profile:money_transfer' %}" class="side" id="transfer">Money Transfer</a> <br> <br>

                    <a href="{% url 'Profile:loan_app' %}" class="side" id="loan">Loan application</a> <br> <br>

                    <a href="{% url 'Profile:ewallet' %}" class="side" id="ewallet">eWallet&trade;</a> <br> <br>

                    <a href="{% url 'Profile:online_pay' %}" class="side" id="online">Online Payment</a> <br> <br>

                    <a href="{% url 'Profile:settings' %}" class="side" id="settings">Account settings</a> <br> <br>

                    <a href="{% url 'Profile:edit_detail' %}" class="side warning" id="details">Edit account details</a> <br> <br>

                    <a href="{% url 'Profile:delete_account' %}" class="side danger" id="delete">Delete account</a> <br> <br>                
                </section>
                <!-- SIDE PANEL ENDS -->

                {% block bodycontent %}
                {% endblock %}

            </div>

        <!-- FOOTER -->
        <section class="foot">
            <div class="text-center">
                 <i class="" style="color: green"></i>  <a href="" target="_blank"></a>
                <br>
                <i class=""></i>  <a href="" target="_blank"></a>
            </div>
        </section>
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>

templates/sign_in.html
{% extends 'base_layout.html' %}

{% block stylecontent %}
    <style>
        body {
            background-color: aliceblue
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}


{% block bodycontent%}
        
    <div class="container"> 
        <form class="form-control" action="/accounts/login/" method="post">
            {% csrf_token %}
            <h2>Enter login details</h2>

            {{ form }}

            <br>

            <button type="submit" class="btn btn-danger">
                <i class="fa fa-sign-in"></i>
                Login
            </button>

            <br> <br>

            <small class="row">
                <a href="#" class="col text-left">Forgot password?</a>
                <a href="{% url 'accounts:signup' %}" class="col text-right">Create New Account</a>
            </small>
        </form>
    </div>
        
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-login").addClass("active");
        $("input").addClass("form-control");
    </script>
{% endblock %}